'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace IntAsEnumExample.Win.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As IntAsEnumExample.Win.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New IntAsEnumExample.Win.Properties.Settings())), IntAsEnumExample.Win.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return IntAsEnumExample.Win.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
